//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.12.18 at 03:07:31 PM EET 
//


package dictionary;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import java.util.GregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="english" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="romanian" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="update_date" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "english",
    "romanian",
    "updateDate"
})
@XmlRootElement(name = "word")
public class Word {

    @XmlElement(required = true)
    protected String english;
    @XmlElement(required = true)
    protected String romanian;
    @XmlElement(name = "update_date", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar updateDate;

    /**
     * Gets the value of the english property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEnglish() {
        return english;
    }

    /**
     * Sets the value of the english property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEnglish(String value) {
        this.english = value;
    }

    /**
     * Gets the value of the romanian property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRomanian() {
        return romanian;
    }

    /**
     * Sets the value of the romanian property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRomanian(String value) {
        this.romanian = value;
    }

    /**
     * Gets the value of the updateDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getUpdateDate() {
        return updateDate;
    }

    /**
     * Sets the value of the updateDate property.
     *
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setUpdateDate(XMLGregorianCalendar value) {
        this.updateDate = value;
    }

}
